[package]
name = "nanobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1", features = [ "attributes" ] }
axum = "0.6.1"
clap = { version = "4.0.27", features = ["cargo", "derive"] }
lazy_static = "1.4.0"
minijinja = { version = "0.26.0", features = ["json", "urlencode", "preserve_order"]}
ontodev_valve = "0.1.14"
regex = "1.7.0"
serde_json = { version = "1.0.89", features = ["preserve_order"] }
serde = { version = "1.0.148", features = ["derive"] }
sqlx = { version = "0.6", features = [  "runtime-async-std-native-tls", "sqlite" ] }
tabwriter = { version = "1.2.1" }
tokio = { version = "1.22.0", features = ["full"] }
toml = { version = "0.5.9" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tree-sitter = "0.20.6"
tree-sitter-sqlrest = { path = "../tree-sitter-sqlrest" }
urlencoding = "2.1.2"
wiring_rs = { git = "https://github.com/ontodev/wiring.rs" } 

[build-dependencies]
cc = "1.0"
