[package]
name = "nanobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["cargo", "derive"] }
ontodev_valve = "0.1.14"
async-std = { version = "1", features = [ "attributes" ] } 
toml = { version = "0.5.9" }
