[package]
name = "nanobot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["cargo", "derive"] }
toml = { version = "0.5.9" }
axum = "0.6.1"
tokio = { version = "1.22.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
minijinja = { version = "0.26.0", features = ["json", "urlencode", "preserve_order"]}
sqlx = { version = "0.6", features = [  "runtime-async-std-native-tls", "sqlite" ] }
async-std = { version = "1", features = [ "attributes" ] }
