on: [push, pull_request]

name: Continuous integration

jobs: 
  build_and_test:
    name: Test nanobot
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 
      - name: Build and test
        run: |
          make deps
          make test
