on: [push, pull_request]

name: Continuous integration

jobs: 
  build_and_test:
    name: Test nanobot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check 
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: nanobot
          path: target/release/nanobot
          if-no-files-found: error 
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: GuillaumeFalourd/assert-command-line-output@v1
        with:
          command_line: ./target/release/nanobot init
          assert_file_path: tests/init.txt
          expected_result: PASSED
