on: [push, pull_request]

name: Continuous integration

jobs: 
  build_and_test:
    name: Test nanobot
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check 
      - run: |
          python --version
          make deps
          make build
      - uses: actions/upload-artifact@v3
        with:
          name: nanobot
          path: target/release/nanobot
          if-no-files-found: error 
      - run: |
          make test
